'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import { Home, Plus, Filter, Heart } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata 제거 (클라이언트 컴포넌트에서는 불가)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className="light">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-neutral-900`}>
        {children}
      </body>
    </html>
  );
}

// Dummy data for demonstration
type Song = {
  id: string;
  title: string;
  nickname: string;
  comment: string;
  votes: number;
  thumbnail: string;
  youtubeId: string;
};

const songs: Song[] = [
  {
    id: "1",
    title: "Song One",
    nickname: "Alice",
    comment: "Great vibes!",
    votes: 12,
    thumbnail: "https://img.youtube.com/vi/ScMzIvxBSi4/hqdefault.jpg",
    youtubeId: "ScMzIvxBSi4",
  },
  {
    id: "2",
    title: "Song Two",
    nickname: "Bob",
    comment: "",
    votes: 8,
    thumbnail: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    youtubeId: "ysz5S6PUM-U",
  },
];

// NavigationBar Component
function NavigationBar() {
  return (
    <nav className="flex items-center justify-between px-4 py-3 bg-white/70 backdrop-blur-md border-b border-neutral-200 sticky top-0 z-30">
      <button className="p-2 rounded-lg hover:bg-neutral-100 transition">
        <Home size={22} />
      </button>
      <div className="flex gap-2">
        <button className="p-2 rounded-lg hover:bg-neutral-100 transition">
          <Plus size={22} />
        </button>
        <button className="p-2 rounded-lg hover:bg-neutral-100 transition">
          <Filter size={22} />
        </button>
      </div>
    </nav>
  );
}

// SongCard Component
function SongCard({
  song,
  onSelect,
  onVote,
  selected,
}: {
  song: Song;
  onSelect: () => void;
  onVote: () => void;
  selected: boolean;
}) {
  return (
    <motion.div
      layout
      whileHover={{ scale: 1.03, boxShadow: "0 8px 32px rgba(0,0,0,0.12)" }}
      className={`relative rounded-2xl overflow-hidden cursor-pointer group transition-all duration-200 border border-neutral-200 ${selected ? "ring-2 ring-blue-400" : ""
        }`}
      onClick={onSelect}
    >
      {/* Blurred thumbnail background */}
      <div
        className="absolute inset-0 bg-cover bg-center"
        style={{
          backgroundImage: `url(${song.thumbnail})`,
          filter: "blur(16px) brightness(0.7)",
        }}
      />
      {/* Glassmorphism overlay */}
      <div className="absolute inset-0 bg-white/10 backdrop-blur-sm" />
      {/* Card content */}
      <div className="relative z-10 flex flex-col justify-between h-40 p-4">
        <div>
          <div className="font-semibold text-white text-lg truncate drop-shadow">
            {song.title}
          </div>
          <div className="text-neutral-200 text-xs mt-1 truncate">
            {song.nickname}
          </div>
          {song.comment && (
            <div className="text-neutral-300 text-xs mt-1 truncate italic">
              {song.comment}
            </div>
          )}
        </div>
        <div className="flex items-center gap-2 mt-2">
          <button
            className="p-1 rounded-full bg-white/20 hover:bg-white/40 transition"
            onClick={e => {
              e.stopPropagation();
              onVote();
            }}
            aria-label="Vote"
          >
            <Heart
              size={18}
              className={song.votes > 0 ? "text-pink-400 fill-pink-400/70" : "text-white"}
              strokeWidth={2}
            />
          </button>
          <span className="text-white text-sm">{song.votes}</span>
        </div>
      </div>
    </motion.div>
  );
}

// SongList Component
function SongList({
  songs,
  onSelect,
  onVote,
  selectedId,
}: {
  songs: Song[];
  onSelect: (id: string) => void;
  onVote: (id: string) => void;
  selectedId: string | null;
}) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-6 py-6">
      {songs.map(song => (
        <SongCard
          key={song.id}
          song={song}
          onSelect={() => onSelect(song.id)}
          onVote={() => onVote(song.id)}
          selected={selectedId === song.id}
        />
      ))}
    </div>
  );
}

// PlayerSection Component
function PlayerSection({
  song,
  onClose,
}: {
  song: Song;
  onClose: () => void;
}) {
  return (
    <AnimatePresence>
      {song && (
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: 40 }}
          transition={{ type: "spring", stiffness: 200, damping: 24 }}
          className="fixed md:static bottom-0 left-0 w-full md:w-[400px] md:max-w-[32vw] z-40 bg-white/80 backdrop-blur-lg border-t md:border-t-0 md:border-l border-neutral-200 shadow-2xl rounded-t-2xl md:rounded-2xl overflow-hidden"
        >
          <div className="flex flex-col">
            {/* Thumbnail */}
            <div className="relative w-full aspect-video bg-neutral-200">
              <img
                src={song.thumbnail}
                alt={song.title}
                className="w-full h-full object-cover"
              />
              <button
                className="absolute top-2 right-2 p-1 bg-white/70 rounded-full hover:bg-white transition"
                onClick={onClose}
                aria-label="Close"
              >
                <svg width="18" height="18" viewBox="0 0 20 20" fill="none">
                  <path d="M6 6l8 8M6 14L14 6" stroke="#222" strokeWidth="2" strokeLinecap="round" />
                </svg>
              </button>
            </div>
            {/* Player */}
            <div className="p-4 flex flex-col gap-2">
              <div className="font-semibold text-lg text-neutral-900 truncate">{song.title}</div>
              <div className="text-neutral-500 text-xs truncate">{song.nickname}</div>
              {song.comment && (
                <div className="text-neutral-700 text-xs italic truncate">{song.comment}</div>
              )}
              <div className="mt-2">
                <iframe
                  className="w-full aspect-video rounded-lg border"
                  src={`https://www.youtube.com/embed/${song.youtubeId}?autoplay=1`}
                  allow="autoplay; encrypted-media"
                  allowFullScreen
                  title={song.title}
                />
              </div>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// Main App Layout
export function AppLayout() {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [songList, setSongList] = useState(songs);

  const selectedSong = songList.find(s => s.id === selectedId) || null;

  const handleVote = (id: string) => {
    setSongList(list =>
      list.map(song =>
        song.id === id ? { ...song, votes: song.votes + 1 } : song
      )
    );
  };

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-br from-neutral-50 to-neutral-200">
      <NavigationBar />
      <main className="flex-1 flex flex-col md:flex-row gap-0 md:gap-8 max-w-7xl mx-auto w-full px-4">
        {/* Song List */}
        <div className="flex-1">
          <SongList
            songs={songList}
            onSelect={setSelectedId}
            onVote={handleVote}
            selectedId={selectedId}
          />
        </div>
        {/* Player Section (desktop) */}
        <div className="hidden md:block w-[400px] max-w-[32vw]">
          {selectedSong && (
            <PlayerSection song={selectedSong} onClose={() => setSelectedId(null)} />
          )}
        </div>
      </main>
      {/* Player Section (mobile) */}
      <div className="md:hidden">
        {selectedSong && (
          <PlayerSection song={selectedSong} onClose={() => setSelectedId(null)} />
        )}
      </div>
    </div>
  );
}